require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Supabase client
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

// Health check endpoint
app.get('/', (req, res) => {
  res.json({ 
    message: 'Learn with Jiji API is running!',
    status: 'healthy',
    timestamp: new Date().toISOString()
  });
});

// Main endpoint: Ask Jiji
app.post('/ask-jiji', async (req, res) => {
  try {
    // 1. Validate request
    const { query, user_id } = req.body;
    
    if (!query || !query.trim()) {
      return res.status(400).json({ 
        error: 'Query is required',
        success: false 
      });
    }

    if (!user_id) {
      return res.status(400).json({ 
        error: 'User ID is required',
        success: false 
      });
    }

    // 2. Store the query in database
    const { data: queryData, error: queryError } = await supabase
      .from('queries')
      .insert([
        { 
          user_id: user_id,
          query_text: query,
          created_at: new Date().toISOString()
        }
      ])
      .select()
      .single();

    if (queryError) {
      console.error('Error storing query:', queryError);
      return res.status(500).json({ 
        error: 'Failed to store query',
        success: false 
      });
    }

    // 3. Search for relevant resources (simple keyword matching)
    const searchKeywords = query.toLowerCase();
    const { data: resources, error: resourceError } = await supabase
      .from('resources')
      .select('*')
      .or(`title.ilike.%${searchKeywords}%,description.ilike.%${searchKeywords}%,tags.ilike.%${searchKeywords}%`)
      .limit(5);

    if (resourceError) {
      console.error('Error fetching resources:', resourceError);
    }

    // 4. Generate mocked AI response
    const aiResponse = generateMockedResponse(query, resources || []);

    // 5. Return structured response
    res.json({
      success: true,
      query_id: queryData.id,
      answer: aiResponse.answer,
      resources: aiResponse.resources,
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('Server error:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      success: false,
      message: error.message 
    });
  }
});

// Helper function: Generate mocked AI response
function generateMockedResponse(query, resources) {
  // Simple mocked responses based on keywords
  const lowerQuery = query.toLowerCase();
  
  let answer = '';
  
  if (lowerQuery.includes('rag')) {
    answer = 'RAG (Retrieval-Augmented Generation) is a technique that combines information retrieval with text generation. It works by first retrieving relevant documents from a knowledge base, then using those documents as context for generating accurate responses. This approach helps reduce hallucinations and provides more factual, grounded answers.';
  } else if (lowerQuery.includes('llm') || lowerQuery.includes('language model')) {
    answer = 'Large Language Models (LLMs) are AI models trained on vast amounts of text data to understand and generate human-like text. They use transformer architectures and can perform various tasks like translation, summarization, question-answering, and code generation.';
  } else if (lowerQuery.includes('prompt')) {
    answer = 'Prompt engineering is the practice of crafting effective inputs (prompts) to get desired outputs from AI models. Good prompts are clear, specific, provide context, and may include examples. This skill is crucial for getting the best results from AI systems.';
  } else {
    answer = `Thank you for your question about "${query}". This is a mocked response from Jiji. In a production system, this would be generated by an AI model trained on learning content. Here are some relevant resources that might help you learn more about this topic.`;
  }

  return {
    answer: answer,
    resources: resources.map(r => ({
      id: r.id,
      title: r.title,
      type: r.resource_type,
      description: r.description,
      url: r.file_url,
      thumbnail: r.thumbnail_url
    }))
  };
}

// Get all resources (optional endpoint for testing)
app.get('/resources', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('resources')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) throw error;

    res.json({
      success: true,
      resources: data
    });
  } catch (error) {
    res.status(500).json({ 
      error: error.message,
      success: false 
    });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
  console.log(`📝 API Endpoint: POST http://localhost:${PORT}/ask-jiji`);
});